# Generated by Django 2.2.3 on 2019-07-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190731_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='x',
        ),
        migrations.RemoveField(
            model_name='room',
            name='y',
        ),
        migrations.AddField(
            model_name='room',
            name='coordinates',
            field=models.CharField(default='()', max_length=32),
        ),
    ]
