# Generated by Django 2.2.3 on 2019-07-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190731_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
